### ISSUE TITLE
TypeError: ChatGPT.get_response() missing 1 required positional argument: 'text'

### ISSUE THREAD

**Issue by mactitane** [TheExplainthis/ChatGPT-Tinder-Bot#3]
Hello team,

I have the following issue on the script. Can you please assist? Thanks a lot!

Job "reply_messages (trigger: cron[minute='*/5', second='0'], next run at: 2023-03-12 13:40:00 UTC)" raised an exception
Traceback (most recent call last):
  File "/home/runner/ChatGPT-Tinder-Bot/venv/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/runner/ChatGPT-Tinder-Bot/main.py", line 53, in reply_messages
    response = chatgpt.get_response(content)
TypeError: ChatGPT.get_response() missing 1 required positional argument: 'text'

**Comment by mactitane** [comment]
Any update on this?

**Comment by TheExplainthis** [comment]
The code has been updated and is now ready for use. Thank you.

**Comment by mactitane** [comment]
Hello TheExplainThis. Thanks for this hotfix !
